### ISSUE TITLE
Not able to run jmap, jstack, jcmd on alpine

### ISSUE THREAD

**Issue by yashbhutwala** [docker-library/openjdk#372] opened 2019-11-19 13:02 UTC
This is a follow-up to issue #76.  Some workarounds were suggested in that issue, but the underlying issue was not traiged/resolved.  The workarounds are not possible for me, creating this to triage further 😄

**Comment by davidmontoyago** [comment] 2019-11-21 16:45
Experiencing the same issue on alpine 3.10.2 and openjdk8~=8.222:

```
$ /usr/lib/jvm/java-1.8-openjdk/bin/jcmd 0 Thread.print
1:
com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        at sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:147)
        at sun.tools.jcmd.JCmd.main(JCmd.java:131)
```

**Comment by wglambert** [comment] 2019-11-27 17:39
If you could provide Dockerfiles you're using and a minimal reproducer that would help
What steps did you try from the other thread, I presume `--init`?

And do you encounter this only on Alpine or on `openjdk:8-slim` as well?

**Comment by tianon** [comment] 2019-11-28 00:08
It's also worth pointing out that only OpenJDK 14 has a currently supported Alpine variant (and is EA -- the Alpine variant there will likely go away post GA, as in previous releases).

**Comment by tianon** [comment] 2019-11-28 00:10
To put that another way, for this issue to stay open, it needs to be demonstrated that `openjdk:14-alpine` is affected (because that is the only place this has a chance of getting fixed in our images).

Anyone affected on 8 or similar versions needs to head over to the upstream Alpine Linux support forums because that's whose package you're having issues with (and you'll want to adjust your `Dockerfile` to be `FROM alpine:xxx` and install OpenJDK from there accordingly, as the previous images here did because otherwise you won't get *any* updates).

**Comment by casimirrex** [comment] 2019-12-01 05:53
we are getting the same problem in opejdk.8XXX.alphine. So we are unable to get heap dump from that docker. Not only create heap dump, but also unable to connect visualvm, jconsole.even though we have enabled jmx port as well.

**Comment by yosifkit** [comment] 2019-12-02 23:32
As @tianon noted above, any help for OpenJDK 8 on Alpine Linux needs to go to Alpine support forums (since the Dockerfile was just installing the Alpine provided packaging for OpenJDK 8). The **OpenJDK 8 on Alpine Linux** images hosted on the [Docker Hub](https://hub.docker.com/_/openjdk/) are no longer maintained\*\*. See the ["Supported tags and respective Dockerfile links" section](https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links) for which tags are currently being maintained.

https://github.com/docker-library/openjdk/pull/322#issue-281393009:

> no more OpenJDK 8 Alpine images (Alpine/musl is not officially supported by the OpenJDK project, so this reflects that -- see "Project Portola" for the Alpine porting efforts which I understand are still in need of help)

Since this has not yet been replicated in the `openjdk:14-alpine` image, I'll close.

------------------------

footnote \*\*:
> you'll want to adjust your `Dockerfile` to be `FROM alpine:xxx` and install OpenJDK from there accordingly, as the previous images here did because otherwise you won't get *any* updates

**Closed by yosifkit** 2019-12-02 23:32 UTC

**Comment by jhmartin** [comment] 2020-04-08 23:03
As a google breadcrumb; https://github.com/apangin/jattach is able to generate heap dumps from within an Alpine / OpenJDK8 based container.

**Comment by bookc-man** [comment] 2023-03-22 09:45
run cmd add `--init` is ok

`docker run  --init `
