### ISSUE TITLE
objcopy is missing generating problems with jlink since java version 13

### ISSUE THREAD

**Issue by memorais** [docker-library/openjdk#351] opened 2019-08-23 13:37 UTC
Starting from version 13, jlink seems to need objcopy which is part of binutils package. If we run jlink on oracle tagged images the following error happen:

> Error: java.io.IOException: Cannot run program "objcopy": error=2, No such file or directory

In that case binutils are dependency needed by oracle image work as expected.

**Comment by yosifkit** [comment] 2019-08-23 21:13
Oh! thanks for the report. I found a quick `jlink` example to reproduce and test that it solves the problem:

```console
$ docker run -it --rm openjdk:13-oracle bash
bash-4.2# jlink --no-header-files --no-man-pages --compress=2 --strip-debug --add-modules java.datatransfer,java.desktop,java.logging,java.scripting,java.sql,java.xml,jdk.jsobject,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom --output java-runtime
Error: java.io.IOException: Cannot run program "objcopy": error=2, No such file or directory
bash-4.2# du -hs java-runtime/
8.0K	java-runtime/
bash-4.2# exit
$ docker run -it --rm openjdk:13-oracle bash
bash-4.2# yum install -q -y binutils
install-info: /usr/share/info/dir: could not read (No such file or directory) and could not create (No such file or directory)
install-info: /usr/share/info/dir: could not read (No such file or directory) and could not create (No such file or directory)
install-info: /usr/share/info/dir: could not read (No such file or directory) and could not create (No such file or directory)
install-info: /usr/share/info/dir: could not read (No such file or directory) and could not create (No such file or directory)
install-info: /usr/share/info/dir: could not read (No such file or directory) and could not create (No such file or directory)
bash-4.2# jlink --no-header-files --no-man-pages --compress=2 --strip-debug --add-modules java.datatransfer,java.desktop,java.logging,java.scripting,java.sql,java.xml,jdk.jsobject,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom --output java-runtime
bash-4.2# du -hs java-runtime/
48M	java-runtime/
bash-4.2# 
```

PR incoming shortly!

**Comment by memorais** [comment] 2019-08-23 21:36
Hi, just to clarify some things about that.

At #openjdk channel on IRC (oftc.net) I was wisely pointed out that --strip-debug option since Java 13 change its behavior and from now on could be used another option to do that job (--strip-java-debug-attributes). In your test if you replace --strip-debug for --strip-java-debug-attributes then objcopy will not be used and the error is not presented.

Anyway it still possible to use --strip-debug which need objcopy from binutils, so this package should be added in the container image IMHO.

More information can be found here:
https://bugs.openjdk.java.net/browse/JDK-8219207
https://bugs.openjdk.java.net/browse/JDK-8214796

**Comment by MikaelSmith** [comment] 2020-01-03 20:47
This also applied to alpine images. Is that worth a separate issue?

**Comment by tianon** [comment] 2020-01-03 21:37
Only if it applies to `openjdk:14-alpine`, which is the only currently-supported Alpine version.

**Comment by tianon** [comment] 2020-01-03 21:38
Confirmed that it does apply there -- I'll have a PR open shortly. :+1:

**Comment by tianon** [comment] 2020-01-03 21:39
Although I guess this is also the opportunity to discuss that -- the Alpine variant is tuned for size, and it is as trivial as `apk add --no-cache binutils` to "fix" the issue and it does not affect all users (only those using this particular feature), so IMO there's a pretty strong argument for it being left out "by design".

**Comment by MikaelSmith** [comment] 2020-01-03 21:41
I'm ok with that personally, is there a good to document the optional requirement? I think I only figured out the error message by searching for it and stumbling across this issue.

**Comment by tianon** [comment] 2020-01-14 22:24
To some extent it's already "documented" under the `openjdk:<version>-alpine` heading on https://hub.docker.com/_/openjdk:

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the [`alpine` image description](https://hub.docker.com/_/alpine/) for examples of how to install packages if you are unfamiliar).

(Which is my justification for us not including it.)

**Comment by tianon** [comment] 2022-02-25 01:24
Coming back to this, I still agree with that justification. :smile:

(Finally closing this accordingly.)

**Closed by tianon** 2022-02-25 01:24 UTC
Labels: Request
