### ISSUE TITLE
7u131 throws no such provider SunEC SSLException when running gradlew

### ISSUE THREAD

**Issue by sgo** [docker-library/openjdk#117] opened 2017-05-23 13:15 UTC
Reverted to 7u121 and the issue goes away.
I vaguely recall having a similar issue when I was still using puppet managed build servers and back then I had to update the security configuration file. Maybe something similar is needed here?

**Comment by shinfan** [comment] 2017-05-23 18:51
+1 I have the same issue

**Comment by REPLicated** [comment] 2017-06-08 20:46
This looks like a bug in either the debian build (7u131-2.6.9-2~deb8u1), in IcedTea 2.6.9-2 or even upstream OpenJDK 7u131.

The problem with [https://plugins.gradle.org](https://plugins.gradle.org) in particular is probably triggered by the cipersuite `TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA`.

A possible workaround (which may impact security negatively and cause other problems, I guess) is to disable the ECDSA Algorithm in 
`/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/java.security`:
```
jdk.certpath.disabledAlgorithms=MD2, MD5, RSA keySize < 1024, \
    DSA keySize < 1024, EC keySize < 224, ECDSA
```

**Comment by DanySK** [comment] 2017-06-29 13:06
I can confirm this issue. It is affecting all my Java 7 builds on Travis CI, e.g. https://travis-ci.org/DanySK/gson-extras/jobs/248334021

**Comment by kinghuang** [comment] 2017-07-18 22:07
I believe I'm having a related problem on the `7u131-jdk-alpine` image.

```
java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SupportedEllipticCurvesExtension
```

There's some discussion at https://bugs.launchpad.net/ubuntu/trusty/+source/openjdk-7/+bug/1691126 that suggests it's a regression introduced in OpenJDK 7 by the backport of [JDK-8148516](https://bugs.openjdk.java.net/browse/JDK-8148516), and is fixed by backporting [JDK-8175450](https://bugs.openjdk.java.net/browse/JDK-8175450). I think we have to wait for the equivalent patches in Debian and Alpine for the Docker images.

**Comment by tianon** [comment] 2018-01-03 21:53
Is this still reproducible?  Is this something that's trivially fixed by instead using the `gradle` official image directly?  Is there anything that can actually be changed in the image to fix this, if it isn't already?

**Comment by kinghuang** [comment] 2018-01-03 21:57
I haven't had the problem in the 7u151 image.

**Comment by tianon** [comment] 2018-01-03 22:44
Nice, thanks for confirming! :heart:

**Closed by tianon** 2018-01-03 22:44 UTC

**Comment by Mklueh** [comment] 2018-01-04 02:08
Facing this issue now with openjdk:8u151-jdk-slim-stretch

**Comment by jaypatel512** [comment] 2018-05-08 19:02
Having this problem again with `openjdk-7-jdk (7u171-2.6.13-1~deb7u1)`

**Comment by LGFdev** [comment] 2020-12-01 09:52
Hello, I have the same bug.
My java version:
>java version "1.7.0_261"
>OpenJDK Runtime Environment (IcedTea 2.6.22) (Arch Linux build 7.u261_2.6.22-1-x86_64)
>OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)

and the stack trace
```
java.lang.RuntimeException: java.security.NoSuchProviderException: no such provider: SunEC
	at sun.security.util.ECUtil.getKeyFactory(ECUtil.java:96)
	at sun.security.util.ECUtil.decodePKCS8ECPrivateKey(ECUtil.java:119)
	at sun.security.pkcs11.P11ECKeyFactory.engineGeneratePrivate(P11ECKeyFactory.java:200)
	at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
....
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
	at sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.security.KeyFactory.getInstance(KeyFactory.java:211)
	at sun.security.util.ECUtil.getKeyFactory(ECUtil.java:94)
	... 33 more
```

By chance, it's append on the dev server, not on the prod.
