### ISSUE TITLE
Alpine 3.9

### ISSUE THREAD

**Issue by tholu** [docker-library/openjdk#279] opened 2019-02-01 15:05 UTC
Alpine 3.9 is the new stable series: https://www.alpinelinux.org/posts/Alpine-3.9.0-released.html
I have read #272, and even if Alpine 3.8 provides the same JDK version as Alpine 3.9, wouldn't it make sense to base the Docker images on the newer Alpine?

This is mainly interesting when using the openjdk image as a base image for our own image, where we add additional software via apk.

**Comment by wglambert** [comment] 2019-02-01 17:17
https://github.com/docker-library/openjdk/pull/276

**Comment by tianon** [comment] 2019-02-01 20:35
Closing as a duplicate of #276. :+1:

**Closed by tianon** 2019-02-01 20:35 UTC
Labels: Request

**Comment by tholu** [comment] 2019-02-01 22:10
Thanks, I totally missed that! 👍

**Comment by damianobarbati** [comment] 2020-02-12 16:53
Is there a way to have `openjdk:13-alpine` extend the `alpine:3.11.3` (latest)? I see very old binaries in the currently used alpine image.

**Comment by yosifkit** [comment] 2020-02-12 21:18
@damianobarbati, the answer would basically be the same as https://github.com/docker-library/openjdk/issues/385#issuecomment-573865579; `openjdk:13-alpine` was dropped in https://github.com/docker-library/openjdk/commit/2822f33cda71487d9e16500513f782c30a4dffbb

**Comment by damianobarbati** [comment] 2020-02-12 21:41
Thanks @yosifkit, I see `openjdk:14-alpine` is a lot of versions behind as well.

**Comment by yosifkit** [comment] 2020-02-12 22:25
It was also dropped as of 14 GA (https://github.com/docker-library/openjdk/commit/485e574acc5d1922ff1778884aeecd82539edcbc), so there is only the alpine builds for 15 ea.

**Comment by wglambert** [comment] 2020-02-12 23:13
We have a support matrix of the OpenJDK variants that we maintain https://github.com/docker-library/openjdk/issues/272
