### ISSUE TITLE
Oracle Linux Git Yum Package Very Old

### ISSUE THREAD

**Issue by rcollette** [docker-library/openjdk#353] opened 2019-08-29 17:25 UTC
I use the JDK 12 docker image to do builds in Docker on a Gitlab shell executor (build slave).  Unfortunately, YUM installing git yields a very old version of Git (1.8.x)

I can build git from scratch but if my build server cache is cleared, building git adds quite a bit of time to the build process.

```Dockerfile
FROM openjdk:12.0.2 as base
LABEL maintainer="richard.collette@pb.com"
LABEL type="build"
#YUM git version is old, at 1.8.x currently.  We have to build it to get the newer version.
RUN yum update -y
RUN yum install curl-devel expat-devel gettext-devel openssl-devel zlib-devel make wget -y
RUN yum install gcc perl-ExtUtils-MakeMaker -y
RUN yum remove git -y
WORKDIR /usr/src
RUN wget https://www.kernel.org/pub/software/scm/git/git-2.23.0.tar.gz
RUN tar xzf git-2.23.0.tar.gz
WORKDIR /usr/src/git-2.23.0
RUN make prefix=/usr/local/git all
RUN make prefix=/usr/local/git install
ENV PATH="${PATH}:/usr/local/git/bin"
RUN git --version
```

When I look at other language platforms like .NET core, they provide "full" docker images with the typical suite of cli tools installed, and the "lite" (alpine) runtime versions, and for tools not installed, ubuntu/alpine have current package versions available.

I know there is no separation of JDK and runtime any longer, but it would be nice if there were full and light versions of the JDK containers so for builds, we have the latest commonly installed OS tools (or at least the ability to easily install the latest versions of these tools).

Some of this issue simply goes away going to Alpine since there are current package versions of tooling available for it.  Even with the layer cache cleared installing a current package is quicker than building the cli tools.   But until an official Alpine image is available, it would be helpful to have a "fuller" version of the JDK available for build scenarios that includes up to date cli tools.

**Comment by yosifkit** [comment] 2019-08-29 21:17
Regarding a "fat" version, we'd rather not maintain such an image (duplicate of #311).

As for the old `git` in Oracle Linux packaging, you'd have to take that up with them.  You could use the `adoptopenjdk:12-hotspot-bionic` or `adoptopenjdk:12-openj9-bionic` image since they are based on Ubuntu Bionic.

**Comment by rcollette** [comment] 2019-08-30 01:26
Thank you very much for pointing me to adoptopenjdk.   That was a major help.

No I just use this as the base for building and unit testing (SpringBoot based services)

```Dockerfile
FROM adoptopenjdk/openjdk12:alpine as base
LABEL maintainer="richard.collette@pb.com"
LABEL type="build"
RUN apk add --update --no-cache git bash curl zip
```

And I use `adoptopenjdk/openjdk12:alpine-jre` for running the built application.


And then I

**Closed** 2019-08-30 01:26 UTC
