### ISSUE TITLE
9-jdk image has SSL issues

### ISSUE THREAD

**Issue by keeganwitt** [docker-library/openjdk#145] opened 2017-09-11 23:40 UTC
9-b179-jdk image works fine, but the latest 9-jdk image is unable to make SSL connections in Java.

Here's how you can see the issue, create _TestHttps.java_ with
```java
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;

public class TestHttps {
    public static void main(String[] args) {
        try {
            HttpsURLConnection conn = (HttpsURLConnection) new URL(args[0]).openConnection();
            conn.getResponseCode();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
and run
```sh
javac TestHttps.java
java -cp . TestHttps "https://www.google.com/"
```
You'll get
```
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969)
        at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1436)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1563)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1491)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:320)
        at TestHttps.main(TestHttps.java:10)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
        at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
        at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:330)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:180)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:192)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
        at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1825)
        at java.base/sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1655)
        at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:260)
        at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1086)
        at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1020)
        at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
        ... 8 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
        ... 23 more
```

**Comment by keeganwitt** [comment] 2017-09-11 23:45
The same test with 9-jre fails with
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:66)
        at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2610)
        at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2634)
        at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(CipherSuite.java:602)
        at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(CipherSuite.java:574)
        at java.base/sun.security.ssl.CipherSuite$BulkCipher.<clinit>(CipherSuite.java:460)
        at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:1074)
        at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(SSLContextImpl.java:354)
        at java.base/sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:42)
        at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:590)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:292)
        at java.base/java.security.Provider$Service.getImplClass(Provider.java:1844)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1820)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:169)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
        at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
        at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
        at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:86)
        at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.base/java.net.URL.openConnection(URL.java:1051)
        at TestHttps.main(TestHttps.java:9)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
        ... 26 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
        at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:324)
        at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
        ... 26 more
```

**Comment by aiannucci** [comment] 2017-09-11 23:49
Faced same issue today with latest image 9-jdk

**Comment by yosifkit** [comment] 2017-09-12 16:23
Works fine with `jdk-slim` or `jre-slim`, so there is something in the non-headless package that breaks things.

**Comment by mjw99** [comment] 2017-09-13 19:33
Seeing this downstream with a Maven project on Bitbucket's pipelines.

**Comment by carlossg** [comment] 2017-09-21 12:58
Easy reproducer with maven image in https://github.com/carlossg/docker-maven/issues/50

    docker run -it --rm maven:3-jdk-9 mvn dependency:tree

**Comment by queer** [comment] 2017-09-25 17:26
Seeing this in the current 9-jre image as well.

**Comment by eolivelli** [comment] 2017-10-02 10:14
I got this issue as well
this is a showstopper for upgrading the build pipeline to jdk9
any news ?

**Comment by philwebb** [comment] 2017-10-03 17:19
> It looks like the `cacerts` file in JDK 9 release (b181) is empty. It wasn't for the last version I tested (b176). I had to copy the truststore from b176 to make my builds pass again (reaching external https repos).

https://twitter.com/CedricChampeau/status/913679310896156672

**Comment by chiralsoftware** [comment] 2017-10-05 18:37
My workaround to this: I have JDK 8 installed. I went in to JDK9_HOME/lib/security and did:

```
rm cacerts
ln -s /etc/ssl/certs/java/cacerts 
```

Problem solved. The cacerts file that comes with 181 is empty. After making that fix, Maven works as expected.

**Comment by yosifkit** [comment] 2017-10-05 18:44
@chiralsoftware, I apparently don't understand how that fixes it; the file `/usr/lib/jvm/java-9-openjdk-amd64/lib/security/cacerts` is already a symlink to `/etc/ssl/certs/java/cacerts`.

```console
$ docker run -it --rm openjdk:9-jdk bash
root@c555aa9be1c4:/# find / -name cacerts
/etc/default/cacerts
/etc/ssl/certs/java/cacerts
/usr/lib/jvm/java-9-openjdk-amd64/lib/security/cacerts
root@c555aa9be1c4:/# ls -l /usr/lib/jvm/java-9-openjdk-amd64/lib/security/cacerts
lrwxrwxrwx 1 root root 27 Aug 24 17:15 /usr/lib/jvm/java-9-openjdk-amd64/lib/security/cacerts -> /etc/ssl/certs/java/cacerts
root@c555aa9be1c4:/# exit
```

**Comment by chiralsoftware** [comment] 2017-10-05 18:47
@yosifkit , I installed from the .tar.gz file 

`0afa4ff751925e039489b4690667aad746412567ffc71393d6a253001874e592  jdk-9+181_linux-x64_bin.tar.gz`

That did not create the link when I untarred it. Creating that link fixed it. I haven't tried the other package files.

**Comment by yosifkit** [comment] 2017-10-05 19:04
@chiralsoftware, I understand, this image uses the Debian packaging for openjdk, not the tar-gz file directly (we get many more architectures that way).

**Comment by yosifkit** [comment] 2017-10-05 19:05
I did a much regression testing using snapshot.debian.org to install openjdk-9-jdk at the same version, `9-b181-4`. It works fine from introduction of the `-4` version on 24 August 2017 up to and including 6 September 2017 at 00:00:00 UTC and then failed when installed at 7 September 2017 at 00:00:00 UTC.  So I've narrowed it down to package updates during the day of 6 September. The list of installed packages that are different between the two images are as follows:

```diff
diff /tmp/0906-java.txt /tmp/0907-java.txt
94c94,95
< ii  libegl1-mesa:amd64            17.1.5-1                amd64        free implementation of the EGL API -- runtime
---
> ii  libegl-mesa0:amd64            17.2.0-1                amd64        free implementation of the EGL API -- Mesa vendor library
> ii  libegl1:amd64                 0.2.999+git20170802-3   amd64        Vendor neutral GL dispatch library -- EGL support
105c106
< ii  libgbm1:amd64                 17.1.5-1                amd64        generic buffer management API -- runtime
---
> ii  libgbm1:amd64                 17.2.0-1                amd64        generic buffer management API -- runtime
112,114c113,116
< ii  libgl1-mesa-dri:amd64         17.1.5-1                amd64        free implementation of the OpenGL API -- DRI modules
< ii  libgl1-mesa-glx:amd64         17.1.5-1                amd64        free implementation of the OpenGL API -- GLX runtime
< ii  libglapi-mesa:amd64           17.1.5-1                amd64        free implementation of the GL API -- shared library
---
> ii  libgl1:amd64                  0.2.999+git20170802-3   amd64        Vendor neutral GL dispatch library -- legacy GL support
> ii  libgl1-mesa-dri:amd64         17.2.0-1                amd64        free implementation of the OpenGL API -- DRI modules
> ii  libgl1-mesa-glx               17.2.0-1                amd64        transitional dummy package
> ii  libglapi-mesa:amd64           17.2.0-1                amd64        free implementation of the GL API -- shared library
116a119,121
> ii  libglvnd0:amd64               0.2.999+git20170802-3   amd64        Vendor neutral GL dispatch library
> ii  libglx-mesa0:amd64            17.2.0-1                amd64        free implementation of the OpenGL API -- GLX vendor library
> ii  libglx0:amd64                 0.2.999+git20170802-3   amd64        Vendor neutral GL dispatch library -- GLX support
144c149
< ii  libllvm4.0:amd64              1:4.0.1-3               amd64        Modular compiler and toolchain technologies, runtime library
---
> ii  libllvm5.0:amd64              1:5.0-1                 amd64        Modular compiler and toolchain technologies, runtime library
199c204
< ii  libwayland-egl1-mesa:amd64    17.1.5-1                amd64        implementation of the Wayland EGL platform -- runtime
---
> ii  libwayland-egl1-mesa:amd64    17.2.0-1                amd64        implementation of the Wayland EGL platform -- runtime
```

I don't really know which of these packages could affect the java ca-certificates file generation. :confused:

**Comment by fdesu** [comment] 2017-10-06 21:09
The same on my Fedora 26.
I have JDK 9 installed from `jdk-9+181_linux-x64_bin.tar.gz` as well as @chiralsoftware, the latest stable version built from openjdk hg also has an empty (32 bytes `cacerts`?) file.

Making a symlink to `/etc/pki/java/cacerts` fixed a problem in my case, however, could anyone say what this "broken" file is? A broken symlink?

**Comment by tianon** [comment] 2017-10-06 21:11
@fdesu @chiralsoftware please take discussions of upstream's broken release tarball elsewhere; this issue is discussing a separate issue with the `openjdk:9` Docker image which stems from the Debian package it is built from -- the seemingly similar issue with upstream's tarball is not likely to be related, and should be reported to the upstream OpenJDK project instead

**Comment by tianon** [comment] 2017-10-12 00:31
Given @yosifkit's diff in https://github.com/docker-library/openjdk/issues/145#issuecomment-334561903, it appears this is somehow related to OpenGL, which is bizarre.  That diff (with the timestamps for http://snapshot.debian.org) is probably enough for filing an issue in Debian to see if the Debian Java team can make heads or tails of what's going on here (and why it works with `openjdk-9-jdk-headless` but not `openjdk-9-jdk`).

**Comment by freakyy85** [comment] 2017-10-14 10:32
having the same problem. would be nice if this could be fixed. thanks.

**Comment by freakyy85** [comment] 2017-10-15 05:18
or does anyone know a fix for this?

**Comment by snakey1980** [comment] 2017-10-15 15:49
@freakyy85 Is it possible for your CI builder to use one of the -slim ones?  I switch to 9-jdk-slim to fix my builds.

**Comment by freakyy85** [comment] 2017-10-15 17:27
oh yes i can. thanks the slim versions have fixed everything!! :)

**Comment by aaron-haskins** [comment] 2017-10-19 17:02
@philwebb, you are right, _cacerts_ keystore is empty in OpenJDK 9. It is a [known issue](http://www.oracle.com/technetwork/java/javase/9-0-1-relnotes-3883752.html#JDK-8189131), see [here](http://bugs.java.com/view_bug.do?bug_id=JDK-8189131) for more details.

**Comment by mikaelhg** [comment] 2017-12-29 20:56
@keeganwitt Have you tried running your repro case with 

```bash
java -Djavax.net.ssl.trustStorePassword=changeit -cp . TestHttps "https://www.google.com/"
```

**Comment by adamvoss** [comment] 2017-12-29 22:38
@keeganwitt I just tried it.  No exception is thrown with your command while `java -cp . TestHttps "https://www.google.com/"` does throw.

**Comment by keeganwitt** [comment] 2017-12-30 00:42
@mikaelhg @adamvoss I got tired of waiting for Oracle to fix, so I overwrote the trust store with the trust store from Java 8 in the Java 9 images of [gradle](https://hub.docker.com/_/gradle/) and [groovy](https://hub.docker.com/_/groovy/).  It'll be fixed in [9.0.4](https://bugs.java.com/view_bug.do?bug_id=JDK-8189131), which maybe is coming [January](https://bugs.openjdk.java.net/projects/JDK/versions/19229)?

**Comment by mikaelhg** [comment] 2017-12-30 09:16
Looking at the behaviour of JDK's `keytool` a bit deeper, it looks like `openjdk:9-jdk-slim`'s `cacerts` file was produced with JDK 8's `keytool`, while `openjdk:9-jdk-slim` file was produced usign JDK 9's keytool. What's changed in the default behaviour?

**Comment by mikaelhg** [comment] 2017-12-30 11:01
In Debian's `org.debian.security.KeyStoreHandler#load`, they call `java.security.KeyStore#getInstance(java.lang.String)` with the parameter `java.security.KeyStore#getDefaultType`, which is read from configuration file `$JAVA_HOME/conf/security/java.security` under the parameter `keystore.type`.

In Java 8, this defaulted to `jks` while the new Java 9 configuration says `pkcs12`.

Verification:

```java
/*
  KeyStore check by @mikaelhg
  javac --release 8 GenerateKeystore.java
  
 */

import java.io.ByteArrayOutputStream;
import java.security.KeyStore;
import java.util.*;

class GenerateKeystore {

    private static void storeAndPrint(final KeyStore keyStore, final String password) throws Exception {
        final ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            if (null == password) {
                keyStore.store(baos, null);
            } else {
                keyStore.store(baos, password.toCharArray());
            }
            final byte firstByte = baos.toByteArray()[0];
            System.out.printf("%15s - %02x\n", password, firstByte);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private static void testKeyStore(final KeyStore keyStore) throws Exception {
        keyStore.load(null, null);
        storeAndPrint(keyStore, "randompassword");
        storeAndPrint(keyStore, "changeit");
        storeAndPrint(keyStore, "");
    }

    public static void main(String[] args) throws Exception {
        final String[] types = {"JKS", "PKCS12", KeyStore.getDefaultType()};
        for (final String storeType : types) {
            System.out.printf("\n%s\n", storeType);
            final KeyStore keyStore = KeyStore.getInstance(storeType);
            testKeyStore(keyStore);
        }
    }

}
```

And output:

```text
$ /usr/lib/jvm/java-9-openjdk-amd64/bin/java -cp . GenerateKeystore

JKS
 randompassword - fe
       changeit - fe
                - fe

PKCS12
 randompassword - 30
       changeit - 30
                - 30

pkcs12
 randompassword - 30
       changeit - 30
                - 30

$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp . GenerateKeystore

JKS
 randompassword - fe
       changeit - fe
                - fe

PKCS12
 randompassword - 30
       changeit - 30
                - 30

jks
 randompassword - fe
       changeit - fe
                - fe

```

**Comment by queer** [comment] 2018-01-13 10:15
This issue no longer shows up for me in `9-jdk-slim` with the first test-case:

```
->  docker run -it --rm openjdk:9-jdk-slim bash
root@d771607bc79c:/# cat > TestHttps.java
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;

public class TestHttps {
    public static void main(String[] args) {
        try {
            HttpsURLConnection conn = (HttpsURLConnection) new URL(args[0]).openConnection();
            System.out.println("Response: " + conn.getResponseCode());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
root@d771607bc79c:/# javac TestHttps.java
root@d771607bc79c:/# java -cp . TestHttps "https://www.google.com/"
Response: 200
```

`java`/`javac` info:

```
root@d771607bc79c:/# java -version
openjdk version "9.0.1"
OpenJDK Runtime Environment (build 9.0.1+11-Debian-1)
OpenJDK 64-Bit Server VM (build 9.0.1+11-Debian-1, mixed mode)
root@d771607bc79c:/# javac -version
javac 9.0.1
```

**Comment by ThStock** [comment] 2018-01-17 14:08
Java 9.0.4 has been released
* http://jdk.java.net/9/
* http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

**Comment by Wintermute1** [comment] 2018-02-13 17:38
Has this been resolved with Java 9.04?

**Comment by yosifkit** [comment] 2018-02-13 19:19
9.0.4 is not yet available in Debian packaging: https://packages.debian.org/sid/openjdk-9-jdk, but it is available in the windows images: https://github.com/docker-library/openjdk/commit/41532fd149c05cb3bbc0c143bfcfa4589f1c3a61.

**Comment by Wintermute1** [comment] 2018-02-13 19:22
ah ok thanks @yosifkit  - any idea when it will be available?

**Comment by yosifkit** [comment] 2018-02-13 21:51
@Wintermute1, sorry, I don't have any insight into when the Debian OpenJDK maintainers will update their version.

**Comment by sureshg** [comment] 2018-02-13 23:11
This is fixed in jdk10. From the jdk 10 release note, The OpenJDK 9 binary for Linux x64 contains an empty cacerts keystore. This prevents TLS connections from being established because there are no Trusted Root Certificate Authorities installed. As a workaround for OpenJDK 9 binaries, users had to set the javax.net.ssl.trustStore System Property to use a different keystore.

"JEP 319: Root Certificates" [1] addresses this problem by populating the cacerts keystore with a set of root certificates issued by the CAs of Oracle's Java SE Root CA Program.

[1] https://bugs.openjdk.java.net/browse/JDK-8191486

**Comment by mikaelhg** [comment] 2018-02-14 05:33
@sureshg Are you sure that the bug you quoted is relevant to this case, as the relevant images use Debian's way of populating the cacerts file in any case? If the file is missing when Debian's cacerts generation is called, the JDK9 defaults to creating a `pkcs12` format cacerts file, while JDK8 defaulted to the `jks` format. These two formats are treated differently, and accessing the `pkcs12` format cacerts file from `java.net` SSL code requires explicitly setting the keystore password in `-Djavax.net.ssl.trustStorePassword=changeit`?

**Comment by oflebbe** [comment] 2018-04-15 19:54
One part of the upstream issue is resolved, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894979 .
However simply running apt-get update; apt-get upgrade ; does not work for now. Please run 
rm /etc/ssl/certs/java/cacerts ; update-ca-certificates -f 
in order to fix the certs, for now. Reported this to upstream

**Comment by sohailalam2** [comment] 2018-04-25 13:17
Hello... what's the ETA for resolving this issue? 
Its open for over 7 months and none of the workarounds really solves it 😞 

I am having the same issue with java 9 in docker `FROM openjdk:9-jdk`

```bash
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
 at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:214) ~[na:na]
 at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1969) ~[na:na]
 at java.base/sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921) ~[na:na]
 at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904) ~[na:na]
 at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1436) ~[na:na]
 at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[na:na]
 at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.5.jar!/:4.5.5]
```

**Comment by mikaelhg** [comment] 2018-04-25 13:39
Well, it's been resolved in upstream, because rebuilding 9-jdk from what's in the repo currently produces a working cacerts file. We'd only need someone to rebuild and reupload the official docker-library images.

**Comment by mikaelhg** [comment] 2018-04-28 14:46
Somewhat off topic: the new ubuntu:18.04 images have the same issue, with openjdk-11-jdk-headless installed.

**Comment by koppor** [comment] 2018-05-02 10:07
Another workaround with all certificates available (from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894979)

```
$ sudo apt install openjdk-8-jre
$ sudo rm /etc/ssl/certs/java/cacerts
$ sudo update-ca-certificates --fresh
```

> This works because /etc/ca-certificates/update.d/jks-keystore prefers OpenJDK 8 over OpenJDK 9.

**Comment by mikaelhg** [comment] 2018-05-10 16:31
Verified that the image `c5eef58c8a2f` created at `2018-05-05T11:07:30+03:00` fixes the problem, so this ticket can be closed.

**Comment by tianon** [comment] 2018-05-10 16:47
Awesome, thanks @mikaelhg!

**Closed** 2018-05-10 16:48 UTC
Labels: Issue

**Comment by abelhOrihuela** [comment] 2018-06-06 05:02
sudo apt install openjdk-8-jre
sudo rm /etc/ssl/certs/java/cacerts
sudo update-ca-certificates --fresh

**Comment by Benjapy** [comment] 2018-07-08 00:36
Thanks abelhOrihuela!! it's work now!!!

**Comment by JamesYeoman** [comment] 2018-08-30 13:02
I found that by doing an update and upgrade of apt-get, the ca-certs end up being updated and so the SSL issues were fixed

**Comment by heroInCommunity** [comment] 2018-12-05 16:20
It seems that openjdk:11.0.1-jre-slim does not work with custom truststores(`javax.net.ssl.trustStore`) and keystores(`javax.net.ssl.keyStore`) of pkcs12 format, only with JKS format.
Spent 1 day trying different workarounds. Reverted stores to use JKS.

**Comment by mikaelhg** [comment] 2018-12-05 16:50
@heroInCommunity, it sounds like it's a different issue, so your best bet might be to open a new issue and include a reproduction. If you do, please tag me in a comment or something, as I'll need to devise a workaround if the fix is a long time coming.
