### ISSUE TITLE
Java 9 on Alpine image

### ISSUE THREAD

**Issue by bobvandette** [docker-library/openjdk#151] opened 2017-10-27 18:54 UTC
Is anyone working on a Java 9 alpine image?

**Comment by yosifkit** [comment] 2017-10-27 20:44
Same answer as https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389 regarding JDK8 bumps.  Closing as duplicate of https://github.com/docker-library/openjdk/issues/100.

Related issues: https://github.com/docker-library/openjdk/issues/136, https://github.com/docker-library/openjdk/issues/140

**Closed by yosifkit** 2017-10-27 20:44 UTC
