### ISSUE TITLE
Provide openjdk8 images optimized for profiles compact1, compact2, compact3

### ISSUE THREAD

**Issue by vroyer** [docker-library/openjdk#240] opened 2018-10-10 16:07 UTC
In order to reduce openjdk 8 docker image footprint, could you provide openjdk 8 lateset images for compact profiles compact1, compact2 and compact3 (like in [ofayau/docker-openjdk](https://github.com/ofayau/docker-openjdk)) ?

See [here]( https://www.oracle.com/technetwork/java/embedded/resources/tech/compact-profiles-overview-2157132.html) for information about java 8 profiles.

**Comment by tianon** [comment] 2018-10-10 18:30
Duplicate of https://github.com/docker-library/openjdk/issues/12.

**Comment by tianon** [comment] 2018-10-10 18:30
(TLDR, this is difficult for us to implement on Java 8 given that our builds there come straight from Debian and they don't do anything special for this)

**Closed by tianon** 2018-10-10 18:30 UTC
Labels: Request
