### ISSUE TITLE
Do we have any plans to make openjdk:11-alpine

### ISSUE THREAD

**Issue by arvasrikanth** [docker-library/openjdk#313] opened 2019-05-10 12:13 UTC
For JDK8, JDK 13 alpine based images are available, Are there any plans to make openJDK11 which is based on alpine.
If not are there any reasons why it is skipped?

**Comment by tianon** [comment] 2019-05-10 15:16
Duplicate of #211 (see especially https://github.com/docker-library/openjdk/issues/211#issuecomment-438173628)

See also https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754

**Closed by tianon** 2019-05-10 15:16 UTC

**Comment by oharaandrew314** [comment] 2020-01-29 20:10
For those googling in, the `11-jdk-slim` tag might be a good workaround.
