### ISSUE TITLE
arm32v7/openjdk:8-jre is no longer available ?

### ISSUE THREAD

**Issue by riteshadval** [docker-library/openjdk#284] opened 2019-02-28 17:13 UTC
we were using this and today can no longer pull the image, our builds are failing because of this

riteshadval$ docker pull arm32v7/openjdk:8-jre
8-jre: Pulling from arm32v7/openjdk
no matching manifest for unknown in the manifest list entries

are we suppose to now use arm32v7/openjdk:8-jre-stretch, thats seems to be ok to download but removing tag like arm32v7/openjdk:8-jre not a good idea when people are using images in wild.

**Comment by wglambert** [comment] 2019-02-28 17:59
Duplicate of https://github.com/docker-library/openjdk/issues/278#issuecomment-459864732
>Looks like the 8 variants have been failing to build on `arm32v7` for a while: :disappointed:
>. . .
>There's something quirky going on with the Debian package we're pulling from, unfortunately (and it seems to not affect `amd64` for whatever reason).

You can grab the archived one from https://github.com/docker-library/repo-info/blob/master/repos/openjdk/remote/8-jre.md#openjdk8-jre---linux-arm-variant-v7
>$ docker pull openjdk@sha256:5fad3f3989f1e96c2cb2e030468842cba7b28f560488f5847cbbaa4d960825f4

**Closed** 2019-03-05 00:20 UTC
