### ISSUE TITLE
No alpine version available for 8u232

### ISSUE THREAD

**Issue by mydata** [docker-library/openjdk#368] opened 2019-11-01 19:19 UTC
Is there any reason why alpine version was not released for openjdk8u232? the latest one we currently use is openjdk8u191. Any suggestions around how to use upgraded version?

**Comment by yosifkit** [comment] 2019-11-01 19:49
Duplicate of #363

> Alpine isn't officially supported by the OpenJDK project

**Closed by yosifkit** 2019-11-01 19:49 UTC
