### ISSUE TITLE
Why not the "official" Java?

### ISSUE THREAD

**Issue by aadrian** [docker-library/openjdk#36] opened 2015-05-15 15:26 UTC
If you call this the "official" repo, why not use the "official" version of Java? i.e. the "oracle jdk" ?

Most users will still need that version, not "open jdk".

Thank you.

**Comment by tianon** [comment] 2015-05-15 15:28
This is a duplicate of https://github.com/docker-library/java/issues/31.

https://github.com/docker-library/official-images/issues/625#issuecomment-87734364 is another useful comment about why we can't package the Oracle JDK, as is https://github.com/docker-library/docs/pull/203/files (which is part of the official documentation for this image now).

**Comment by aadrian** [comment] 2015-05-15 15:36
It can be, but it's still not useful and just confusing.

I know that the major distros did that, but I still have to install the Oracle JDK and most people coding Java need that, not the "open" version, so the problem still exists - We just have now more work to do.

I was hoping that Docker can solve this problem, since it's not a "distribution" in the same sense the Linux distributions are.

**Comment by md5** [comment] 2015-05-15 15:38
@aadrian I disagree with your contention that "most users" need to install the Oracle JDK.

**Comment by tianon** [comment] 2015-05-15 15:38
Oracle's JDK isn't licensed such that we're allowed to redistribute it
without a specific exemption from Oracle, same as any other distribution.

In my own Java usage, I've found that the OpenJDK suits my needs really
well, especially being that it's literally defined as "The Reference
Implementation for the Java language".

**Comment by aadrian** [comment] 2015-05-15 15:42
@md5 @tianon so far I saw no commercial installation to use the OpenJDK. A few with the IBM one, but none with OpenJDK. The requirement is quite clear in most commercial projects I've worked on or I'm aware of.

**Comment by md5** [comment] 2015-05-15 20:29
@aadrian I believe you'll also find in those same environments that they have support contracts with the JVM vendor.

Creating a set of Dockerfiles based that align closely with the official Docker `java` images would be pretty easy to do as demonstrated by existing Docker images using the WebUpd8 (cf. http://www.webupd8.org/2015/02/install-oracle-java-9-in-ubuntu-linux.html). Using those Dockerfiles to build private images within the walls of organizations that are able to legal use them would also be possible. But distributing Docker images based on the Oracle JDK publicly is pretty clearly not allowed by their licensing.

**Comment by aadrian** [comment] 2015-05-15 20:46
> But distributing Docker images based on the Oracle JDK publicly is pretty clearly not allowed by their licensing.

But you don't have binary images here, do you? All I see in this Git repo are config (docker) files :)

**Comment by yosifkit** [comment] 2015-05-15 20:52
Yes, but we don't distribute these docker files, we distribute docker images with everything installed.

**Comment by aadrian** [comment] 2015-05-15 21:02
> Yes, but we don't distribute these docker files, we distribute docker images with everything installed.

Why not? Would it be too slow to build the image out of it?

**Comment by blop** [comment] 2015-08-31 13:20
+1

**Comment by aadrian** [comment] 2016-02-02 16:22
It looks like those images are there now https://github.com/oracle/docker-images and https://github.com/oracle/docker-images/tree/master/OracleJDK so no need to use the "reduced" ones.

**Comment by rsutormin** [comment] 2016-02-18 23:42
@aadrian, Nope, they still require to download and manually put tar-gz file to repo folder. It means you still can not register this or inherited image in public docker-hub.

**Comment by tianon** [comment] 2016-08-29 17:58
See also https://github.com/docker-library/docs/pull/203 and https://github.com/docker-library/docs/pull/660.

**Closed by tianon** 2016-08-29 17:58 UTC
