### ISSUE TITLE
Missing class in latest pull of openjdk:8u212-jre-slim

### ISSUE THREAD

**Issue by james-r-smith** [docker-library/openjdk#336] opened 2019-06-14 14:34 UTC
I'm using `openjdk:8u212-jre-slim`, and it was working perfectly for me. After downloading the image again a few weeks later, however, I'm now receiving the following exception when running JavaMelody:

```
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager
```

It appears that this [was an issue](https://github.com/javamelody/javamelody/issues/699) with Alpine Linux in the past. I'm now experiencing it with the Debian image.

You can replicate the exception by running JavaMelody (`1.77.0`) inside Docker (`openjdk:8u212-jre-slim`).

**Comment by tianon** [comment] 2019-06-14 15:31
Duplicate of #333 and #335.

**Closed by tianon** 2019-06-14 15:31 UTC
