### ISSUE TITLE
openjdk:8u201-jdk-alpine and chpasswd

### ISSUE THREAD

**Issue by AllenConquest** [docker-library/openjdk#300] opened 2019-04-05 23:47 UTC
When building a Dockerfile that used chpasswd the following error is seen:

Password: chpasswd: PAM: Authentication failure

Using the 8u191 image works fine, so something has changed in the upgrading of this Dockerfile.

**Comment by tianon** [comment] 2019-04-08 23:06
I can't reproduce:

```console
$ docker pull openjdk:8-jdk-alpine
8-jdk-alpine: Pulling from library/openjdk
Digest: sha256:98028f86019f141cc9fd4f7e076b5411fea9f8d96b82aca84654f21426f127ed
Status: Image is up to date for openjdk:8-jdk-alpine

$ docker run -it --rm openjdk:8-jdk-alpine
/ # echo root:test | chpasswd
chpasswd: password for 'root' changed
```

**Comment by AllenConquest** [comment] 2019-04-09 19:58
@tianon I have found it was because I was installing the shadow package and using groupadd and useradd to add a new group and user.

docker run -it --rm openjdk:8-jdk-alpine
/ # apk add -q shadow
/ # echo root:test | chpasswd
Password: chpasswd: PAM: Authentication failure

**Comment by tianon** [comment] 2019-04-12 20:54
Closing in favor of the more-appropriate upstream issue: https://github.com/alpinelinux/docker-alpine/issues/7 :+1:

(This isn't really something we can fix in this image -- the fix needs to come from Alpine upstream.)

**Closed by tianon** 2019-04-12 20:54 UTC
