### ISSUE TITLE
java path for javaws

### ISSUE THREAD

**Issue by jangaraj** [docker-library/openjdk#50] opened 2015-09-24 09:41 UTC
java:6 container:

```
root@f8fadf3e006d:/# javaws /my.jnlp
/usr/bin/javaws: line 93: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java: No such file or directory
```

Because:

```
root@f8fadf3e006d:/# head /usr/bin/javaws
#!/bin/bash

JAVA=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
```

Probably it should be:

```
JAVA=/usr/bin/java
```

/usr/bin/java is 6 version in this case:

```
root@f8fadf3e006d:/# /usr/bin/java -version
java version "1.6.0_36"
OpenJDK Runtime Environment (IcedTea6 1.13.8) (6b36-1.13.8-1~deb7u1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```

**Comment by md5** [comment] 2015-09-24 16:06
@jangaraj Which `java` image are you using? I don't see multiple versions of Java in any of the current images, though I think this may have been a problem like a year ago:

```console
$ for img in java:6 java:7 java:8; do for variant in jre jdk; do docker pull "$img-$variant" &>/dev/null; (set -x; docker run --rm "$img-$variant" find -name java -executable -ls); done; done
+ docker run --rm java:6-jre find -name java -executable -ls
   208    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:06 ./etc/ssl/certs/java
   744    0 lrwxrwxrwx   1 root     root           46 Sep 10 08:06 ./etc/alternatives/java -> /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java
  1867    4 drwxr-xr-x   2 root     root         4096 Feb 26  2012 ./usr/share/java
  8603    0 lrwxrwxrwx   1 root     root           15 Aug 19 15:42 ./usr/lib/jvm/java-6-openjdk-amd64/bin/java -> ../jre/bin/java
   795   40 -rwxr-xr-x   1 root     root        37728 Aug 19 15:42 ./usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java
  9352    0 lrwxrwxrwx   1 root     root           22 Sep 10 08:06 ./usr/bin/java -> /etc/alternatives/java
+ docker run --rm java:6-jdk find -name java -executable -ls
   244    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:00 ./etc/ssl/certs/java
   784    0 lrwxrwxrwx   1 root     root           46 Sep 10 08:00 ./etc/alternatives/java -> /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java
  2765    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:00 ./usr/share/java
 15973    0 lrwxrwxrwx   1 root     root           15 Aug 19 15:42 ./usr/lib/jvm/java-6-openjdk-amd64/bin/java -> ../jre/bin/java
   901   40 -rwxr-xr-x   1 root     root        37728 Aug 19 15:42 ./usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java
 20694    0 lrwxrwxrwx   1 root     root           22 Sep 10 08:00 ./usr/bin/java -> /etc/alternatives/java
+ docker run --rm java:7-jre find -name java -executable -ls
   223    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:13 ./etc/ssl/certs/java
   794    0 lrwxrwxrwx   1 root     root           46 Sep 10 08:13 ./etc/alternatives/java -> /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  2828    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:13 ./usr/share/java
 12496    0 lrwxrwxrwx   1 root     root           15 Jul 24 15:06 ./usr/lib/jvm/java-7-openjdk-amd64/bin/java -> ../jre/bin/java
   829    8 -rwxr-xr-x   1 root     root         6368 Jul 24 15:06 ./usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
 13779    0 lrwxrwxrwx   1 root     root           22 Sep 10 08:13 ./usr/bin/java -> /etc/alternatives/java
+ docker run --rm java:7-jdk find -name java -executable -ls
   243    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:09 ./etc/ssl/certs/java
   824    0 lrwxrwxrwx   1 root     root           46 Sep 10 08:09 ./etc/alternatives/java -> /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
  3710    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:08 ./usr/share/java
 17626    0 lrwxrwxrwx   1 root     root           15 Jul 24 15:06 ./usr/lib/jvm/java-7-openjdk-amd64/bin/java -> ../jre/bin/java
   920    8 -rwxr-xr-x   1 root     root         6368 Jul 24 15:06 ./usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
 21733    0 lrwxrwxrwx   1 root     root           22 Sep 10 08:09 ./usr/bin/java -> /etc/alternatives/java
+ docker run --rm java:8-jre find -name java -executable -ls
   229    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:21 ./etc/ssl/certs/java
   800    0 lrwxrwxrwx   1 root     root           46 Sep 10 08:21 ./etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  2013    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:21 ./usr/share/java
  9355    0 lrwxrwxrwx   1 root     root           15 Aug  5 10:14 ./usr/lib/jvm/java-8-openjdk-amd64/bin/java -> ../jre/bin/java
   835    8 -rwxr-xr-x   1 root     root         6408 Aug  5 10:14 ./usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  9615    0 lrwxrwxrwx   1 root     root           22 Sep 10 08:21 ./usr/bin/java -> /etc/alternatives/java
+ docker run --rm java:8-jdk find -name java -executable -ls
   205    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:16 ./etc/ssl/certs/java
   801    0 lrwxrwxrwx   1 root     root           46 Sep 10 08:16 ./etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  3717    4 drwxr-xr-x   2 root     root         4096 Sep 10 08:15 ./usr/share/java
 17202    0 lrwxrwxrwx   1 root     root           15 Aug  5 10:14 ./usr/lib/jvm/java-8-openjdk-amd64/bin/java -> ../jre/bin/java
   901    8 -rwxr-xr-x   1 root     root         6408 Aug  5 10:14 ./usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
 21311    0 lrwxrwxrwx   1 root     root           22 Sep 10 08:16 ./usr/bin/java -> /etc/alternatives/java
```

**Comment by md5** [comment] 2015-09-24 16:06
Derp, just saw you said `java:6`. That looks more like a bug in the Debian packaging for Java 6.

**Comment by md5** [comment] 2015-09-24 16:18
Looks like that's actually `java:6-jdk`, since `java:6-jre` doesn't include `javaws`. I also checked the `java:7-jdk` and `java:8-jdk` and they don't include `javaws` at all.

**Comment by md5** [comment] 2015-09-24 16:19
(At least not in the default `PATH`)

**Comment by jangaraj** [comment] 2015-09-24 16:24
Yes, problem is package:
```
root@3a4daf33fe4a:/# apt-get install openjdk-6-jdk
...
root@3a4daf33fe4a:/# javaws
/usr/bin/javaws: line 93: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java: No such file or directory
root@3a4daf33fe4a:/# head /usr/bin/javaws
#!/bin/bash

JAVA=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
...
CP=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar
```

**Comment by md5** [comment] 2015-09-24 17:50
Looks like `javaws` is actually coming from the `icedtea-netx` package. I'm not exactly sure why it's not choosing the right alternative, but this looks like it fixes things:

```console
$ update-alternatives --set javaws /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/javaws
```

**Comment by md5** [comment] 2015-09-24 17:51
I guess this is why:

```console
# update-alternatives --display javaws
javaws - manual mode
  link currently points to /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/javaws
/usr/lib/jvm/java-6-openjdk-amd64/jre/bin/javaws - priority 1061
  slave javaws.1.gz: /usr/lib/jvm/java-6-openjdk-amd64/jre/man/man1/javaws.1.gz
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/javaws - priority 1071
  slave javaws.1.gz: /usr/lib/jvm/java-7-openjdk-amd64/jre/man/man1/javaws.1.gz
Current 'best' version is '/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/javaws'.
```

**Comment by yosifkit** [comment] 2015-09-25 22:00
After a bit of research, I don't think `javaws` should not be installed by default in the java images.  My reasons are as follows: 
- `update-java-alternatives -s java-1.6.0-openjdk-amd64` does not affect `javaws`
- it is not part of the `openjdk-6` source package for debian, but actually from `icedtea-web`
- it is not required to run many `java` applications
- it requires X11 to use

I propose that we add a `--no-recommends` to the `apt-get install` on the java images to clean out unnecessary packages. Here is the list of packages that would be dropped (not including their own dependencies):

```
  dbus libglib2.0-data hicolor-icon-theme libgtk2.0-bin tcpd libxt-dev ttf-dejavu-extra
  icedtea-netx icedtea-6-jre-cacao icedtea-6-jre-jamvm
```

This will mean that users that want it will need to create an image `FROM java:6` with `RUN apt-get update && apt-get install -y icedtea-netx && rm -rf /var/lib/apt/lists/*`, but with [automated builds](https://docs.docker.com/docker-hub/builds/) and [repository links](https://docs.docker.com/docker-hub/builds/#repository-links) it's reasonably easy to have an up-to-date image built `FROM` this one with whatever they need added in.

Given that, I do believe it is packaged improperly in debian to correctly work "out-of-the-box" with just java 6 and that should be a bug filed with the debian packagers, since the default of every other java command in the alternatives list is java 6, rather than java 7.

**Comment by md5** [comment] 2015-09-25 22:13
@yosifkit Sounds good to me. I agree with your reasoning and the proposed change.

**Comment by tianon** [comment] 2016-08-22 19:25
@yosifkit do you still think adding `--no-install-recommends` is worthwhile here?  Should we make a PR?

**Comment by yosifkit** [comment] 2016-08-22 19:49
It might be nice but will probably break a non-zero number of users.

**Comment by tianon** [comment] 2016-08-22 21:34
:hankey:

**Comment by tianon** [comment] 2018-01-03 21:25
Is this still relevant?  Is it still a problem for anyone?

**Comment by tianon** [comment] 2018-04-24 20:45
Closing, since this appears to be resolved.  If it is not, please open a new issue with details about how to reproduce your problem.

**Closed by tianon** 2018-04-24 20:45 UTC
